fullname: Hoare Type Theory
shortname: htt
organization: imdea-software
opam_name: coq-htt
community: false
action: true
coqdoc: false

synopsis: >-
  Hoare Type Theory
description: |-
  Hoare Type Theory (HTT) is a verification system for reasoning about sequential heap-manipulating
  programs. It incorporates Hoare-style specifications via preconditions and postconditions into
  types.

  A Hoare type `{P}x : A{Q}` denotes computations with a precondition `P` and postcondition `Q`,
  returning a value of type `A`. Hoare types are a dependently typed version of monads, as used in
  the programming language Haskell. Monads hygienically combine the language features for pure
  functional programming, with those for imperative programming, such as state or exceptions. In
  this sense, HTT establishes a formal connection between Hoare logic and monads, in the style of
  Curry-Howard isomorphism: every effectful command in HTT has a type which corresponds to the
  appropriate inference rule in Hoare logic, and vice versa, every inference rule in (a version of)
  Hoare logic, corresponds to a command in HTT which has that rule as the type.
authors:
- name: Aleksandar Nanevski
  initial: true
- name: Germán Andrés Delbianco
  initial: false
- name: Alexander Gryzlov
  initial: false

publications:
- pub_url: https://software.imdea.org/~aleks/papers/reflect/reflect.pdf
  pub_title: Structuring the verification of heap-manipulating programs
  pub_doi: 10.1145/1706299.1706331

maintainers:
- name: Alexander Gryzlov
  nickname: clayrat

opam-file-maintainer: fcsl@software.imdea.org

opam-file-version: dev

license:
  fullname: Apache-2.0
  identifier: Apache-2.0
  file: LICENSE

supported_coq_versions:
  text: Coq 8.14 to 8.15
  opam: '{ (>= "8.14" & < "8.16~") | (= "dev") }'

tested_coq_opam_versions:
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{ (>= "1.13.0" & < "1.15~") | (= "dev") }'
  description: |-
    [MathComp ssreflect 1.13 to 1.14](https://math-comp.github.io)
- opam:
    name: coq-fcsl-pcm
    version: '{ (>= "1.5.0" & < "1.6~") | (= "dev") }'
  description: |-
    [FCSL-PCM 1.5](https://github.com/imdea-software/fcsl-pcm)

namespace: htt

keywords:
- name: partial commutative monoids
- name: separation logic

categories:
- name: Computer Science/Data Types and Data Structures

documentation: |-
  ##  References

  * [Partiality, State and Dependent Types](http://software.imdea.org/~aleks/htt/tlca11.pdf)

    Kasper Svendsen, Lars Birkedal and Aleksandar Nanevski. TLCA 2011.

    A semantic model for HTT, with large sigma types.

  * [Structuring the Verification of Heap-Manipulating Programs](http://software.imdea.org/~aleks/htt/reflect.pdf)

    Aleksandar Nanevski, Viktor Vefeiadis and Josh Berfine. POPL 2010.

    This paper introduces what is closest to the current structure of the implementation of HTT.
    It puts emphasis on structuring programs and proofs together, rather than on attacking the
    verification problem using proof automation. It carries out a large case study, verifying the
    congruence closure algorithm of the Barcelogic SAT solver.

    The current implementation differs from what's explained in this paper, in that it uses unary,
    rather than binary postconditions.

  * [Ynot: Dependent Types for Imperative Programs](http://software.imdea.org/~aleks/htt/ynot08.pdf)

    Aleksandar Nanevski, Greg Morrisett, Avi Shinnar, Paul Govereau, Lars Birkedal. ICFP 2008.

    First implementation of HTT as a DSL in Coq, and a number of examples.

  * [A Realizability Model for Impredicative Hoare Type Theory](http://software.imdea.org/~aleks/htt/esop08.pdf)

    Rasmus L. Petersen, Lars Birkedal, Aleksandar Nanevski, Greg Morrisett. ESOP 2008.

    A semantic model for HTT, but without large sigma types.

  * [Abstract Predicates and Mutable ADTs in Hoare Type Theory](http://software.imdea.org/~aleks/htt/esop07.pdf)

    Aleksandar Nanevski, Amal Ahmed, Greg Morrisett, Lars Birkedal. ESOP 2007.

    Adding abstract predicates to HTT.

  * [Hoare Type Theory, Polymorphism and Separation](http://software.imdea.org/~aleks/htt/jfpsep07.pdf)

    Aleksandar Nanevski, Greg Morrisett and Lars Birkedal. JFP 2007.

    Journal version of the ICFP 2006 paper.

  * [Polymorphism and Separation in Hoare Type Theory](http://software.imdea.org/~aleks/htt/icfp06.pdf)

    Aleksandar Nanevski, Greg Morrisett and Lars Birkedal. ICFP 2006.

    The first paper containing a (very impoverished) definition of HTT.
