name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:2.2.0-coq-8.19'
          - 'mathcomp/mathcomp:2.3.0-coq-8.20'
          - 'mathcomp/mathcomp:latest-coq-dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          custom_script: |
            {{before_install}}
            startGroup "Build htt-core dependencies"
              opam pin add -n -y -k path coq-htt-core .
              opam update -y
              opam install -y -j $(nproc) coq-htt-core --deps-only
            endGroup
            startGroup "Build htt-core"
              opam install -y -v -j $(nproc) coq-htt-core
              opam list
            endGroup
            startGroup "Build htt dependencies"
              opam pin add -n -y -k path coq-htt .
              opam update -y
              opam install -y -j $(nproc) coq-htt --deps-only
            endGroup
            startGroup "Build coq-htt"
              opam install -y -v -j $(nproc) coq-htt
              opam list
            endGroup
            startGroup "Uninstallation test"
              opam remove -y coq-htt
              opam remove -y coq-htt-core
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
